site_name: DataGrid
theme: readthedocs
site_url: https://github.com/name

nav:
    - Home: index.md
    - datagrid Module: datagrid.md
    - DataGrid Class: datagrid_class.md
    - Image Class: image.md

plugins:
    - mkdocstrings
